import streamlit as st
from email_module.utils.session import get
from streamlit_quill import st_quill

def render():
    email = get()

    if email.get("result") is None:
        st.info("Awaiting report generation to display preview.")
        return

    # Use the rich text editor to display and allow edits.
    # The initial value is the HTML generated by the EmailBuilder.
    edited_html = st_quill(
        value=email["result"]["html"],
        html=True,  # Work in HTML mode
        key="email_editor"
    )

    # If the user makes any changes, the `edited_html` will be different.
    # We update the session state to ensure the draft uses the latest version.
    if edited_html != email["result"]["html"]:
        email["result"]["html"] = edited_html