import streamlit as st
import io
from email_module.services.email_builder import EmailBuilder
from email_module.utils.session import get

def render():
    email = get()

    st.subheader("Email Configuration")

    st.selectbox("Client", ["TATA Capital"], disabled=True)

    if not st.session_state.get("downloads"):
        st.info("Please generate an audit report in the first tab to configure the email.")
        return

    downloads = st.session_state.downloads

    # Create a file-like object from the generated bytes for EmailBuilder
    excel_file = io.BytesIO(downloads["excel"])
    excel_file.name = downloads["excel_name"]

    # Prevent rebuilding every rerun
    if email.get("result") is None or email.get("filename") != excel_file.name:
        with st.spinner("Extracting data and generating Email Preview..."):
            builder = EmailBuilder(excel_file)
            result = builder.build()

        email["result"] = result
        email["subject"] = result.get("subject", f"Audit Report - {excel_file.name}")
        email["filename"] = excel_file.name
        email["file_bytes"] = downloads["excel"]

    st.divider()
    st.subheader("Email Details")

    email["subject"] = st.text_input("Subject", value=email.get("subject", ""))

    col1, col2 = st.columns(2)
    with col1:
        email["to"] = st.text_input("To", value=email.get("to", ""), placeholder="recipient@example.com")
    with col2:
        email["cc"] = st.text_input("CC", value=email.get("cc", ""), placeholder="manager@example.com")

    st.divider()
    st.markdown("### Attachments")
    
    # Allow the user to select which generated files to attach
    attach_zip = st.checkbox("Attach Complete Package (ZIP)", value=True)
    attach_pdf = st.checkbox("Attach Final Report (PDF)", value=False)
    
    additional_files = st.file_uploader("Additional Attachments (Optional)", accept_multiple_files=True)

    attachments = []
    
    if attach_zip:
        attachments.append({
            "filename": "Audit_Report_Package.zip",
            "content": downloads["zip"]
        })
        
    if attach_pdf:
        attachments.append({
            "filename": downloads["final_name"],
            "content": downloads["final"]
        })

    if additional_files:
        for file in additional_files:
            attachments.append({
                "filename": file.name,
                "content": file.read()
            })

    email["attachments"] = attachments

    for att in attachments:
        size = len(att["content"]) / (1024 * 1024)
        st.success(f"📎 {att['filename']} ({size:.2f} MB)")